### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Akiq2016** [Akiq2016/blog#15]
- [ ] 更新Webpack配置
- [ ] 添加测试 (browserstack)
- [ ] 开发环境 - 远程打包自动化
- [ ] goldwave
- [ ] 单点登录
- [ ] Console使用
- [ ] Network使用
- [ ] Performance使用
- [ ] Memory使用
- [ ] http://blog.teamtreehouse.com/introduction-source-maps
- [ ] http://www.ruanyifeng.com/blog/2013/01/javascript_source_map.html
- [ ] https://segmentfault.com/a/1190000008315937
- [ ] https://juejin.im/post/58293502a0bb9f005767ba2f
- [ ] https://mrshi.gitbooks.io/survivejs_webpack_chinese/chapter3-5.html
- [ ] https://bobscript.com/archives/412/
- [ ] https://juejin.im/post/59db6e7af265da431f4a02ef
- [ ] http://www.zhangxinxu.com/wordpress/2012/10/new-pad-retina-devicepixelratio-css-page/
- [ ] http://blog.csdn.net/cienit/article/details/46430083
- [ ] http://imweb.io/topic/586b2206b3ce6d8e3f9f99ce
- [ ] https://developers.google.com/web/tools/chrome-devtools/network-performance/reference#timing-explanation
- [ ] http://jsfiddle.net/on1kh4o0/
- [ ] http://2ality.com/2013/05/quirk-array-like-objects.html
- [ ] jsonwebtoken
- [ ] https://segmentfault.com/q/1010000000687977/a-1020000000688757
- [ ] Material paginatorIntl: waiting for release
- [ ] https://github.com/angular/material2/issues/5573
- [ ] http://www.html-js.com/article/2518
- [ ] http://www.cnblogs.com/surfaces/p/4360031.html
- [ ] http://www.cnblogs.com/milo-wjh/p/6364138.html
- [ ] https://desandro.github.io/3dtransforms/docs/introduction.html

- [ ] https://addyosmani.com/blog/faster-javascript-memoization/
- [ ] http://ejohn.org/blog/how-javascript-timers-work/#postcomment
- [ ] https://medium.com/@benlesh/rxjs-dont-unsubscribe-6753ed4fda87
- [ ] http://2ality.com/2012/03/signedzero.html
- [ ] https://www.davidbcalhoun.com/2011/when-to-base64-encode-images-and-when-not-to/

- [ ] 象限计划表
- [ ] Google Form表单
- [ ] 多个目标地址的可视化距离
- [ ] 书签系统

**Comment by Akiq2016** [comment]
- [] https://developer.mozilla.org/zh-CN/docs/Web/API/File/Using_files_from_web_applications
- [] http://zyk.ajiao.com/dzkb/255_60.html
- [] http://waterbolik.github.io/jekyll/2015/10/14/MathJax%E8%AF%AD%E6%B3%95%E8%AF%A6%E8%A7%A3
- [] http://www.cnblogs.com/TomXu/archive/2011/12/15/2288411.html#3848276
- [] https://zhuanlan.zhihu.com/v8core
- [] http://greenteapress.com/thinkpython/thinkpython.pdf

**Comment by Akiq2016** [comment]
# 功能点
1. 登陆
需要跟后端进一步沟通：
    1. 目前有两个登陆角色：学生 | 教师
    2. 需要接入已有账号

2. 问卷表单
    1. 列表页
        1. 提供新增表单按钮
        2. 每条明细提供删除和查看功能
    2. 新增问卷表单
        1. 教师权限下，表单头部额外显示以下内容
            1. Input number：设置4方权重：教师&企业&专家&同学
            2. 单选角色：教师|企业|专家
            3. Input number：录入学生的出勤率 知识测试的数据
        2. 页面通用内容
            1. Input text：输入一级标题(有且仅有一个一级项)
            2. Input text：添加二级标题(一或多)
            3. 添加单选题(一或多)
                1. TODO: 选项是否固定？ 比如 固定为 1 3 5 7
                2. 系统写死百分制分值的转换计算方法
                3. 提供删除按钮
            4. Textarea：当前角色的评语（不同角色不同remark字段）

# 需求点解释

### 权重类型
涉及到的权重类型包括角色权重，和表单具体项目权重

1. 角色权重
(有新增"问卷"表单权限的是教师，以下简称用户)用户在新建某份表单的同时，要设置该问卷即将使用的4方比重，用于后续表单数据收集时的计算。也就是说，对某个学生的成绩评定，由4方共同评定，4方的评分占比不同。也就是角色权重。

2. 表单具体项目权重
用户新建表单时，新建具体选择项时 比如某一个选择题时 就去设置好他的权重

### 角色类型
目前有4种角色，主要有账号的是学生和教师，因此企业和专家这两种角色，由教师角色“代理”，他们的表单输入由教师代输，所以教师权限下还可以再去选择角色。


Todo: 能不能继续修改？有没有表单审核？
